client: ainsley.dev
url: https://ainsley.dev
title: Title of the site
description: Description of the site
social:
    facebook:
    instagram:
    linkedIn:
    twitter:
googleAnalytics: UA-PROPERTY_ID
